apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastx-deployment
  labels:
    app: fastx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastx
  template:
    metadata:
      labels:
        app: fastx
    spec:
      containers:
        - name: fastx
          image: 043309334765.dkr.ecr.us-east-2.amazonaws.com/fastx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
