apiVersion: v1
kind: Deployment
metadata:
  name: fastx-deployment
  labels:
    app: fastx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastx
  template:
    labels:
      app: fastx
    spec:
      containers:
        - name: fastx
          image: 043309334765.dkr.ecr.us-east-2.amazonaws.com/fastx-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
