apiVersion: v1
kind: Service
metadata:
  name: fastxservice
  labels:
    app: fastx
spec:
  selector:
    app: fastx
  type: LoadBalancer
  ports:
    - name: fastx-port
      port: 80
      targetPort: 8080
      nodePort: 30090
      protocol: TCP
