name: deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install kubectl
        uses: azure/setup-kubectl@v2.0
        id: install 
        with:
          version: "v1.24.0"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - name: login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: build, tag, push docker image to Amazon ECR
        env:
          # REGISTRY: ${{ steps.login-ecr.outputs.registry }}   
          REGISTRY: 043309334765.dkr.ecr.us-east-2.amazonaws.com    
          REPOSITORY:  fastx-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG  -f ./docks/Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER  --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl apply -f manifests/service.yaml